name: "CI"
on:
  push:
    branches: [ "main", "cert-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      CERTHOSTNAME: test.example
    steps:

      # - name: Setup BATS
      #  uses: mig4/setup-bats@v1
      #  with:
      #    bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v1

      # - name: run script
      #   run: bash script.sh

      - name: Generate Private Key
        run: openssl genpkey -algorithm RSA -out $CERTHOSTNAME.key
      
      - name: Generate CA Certificate
        run: openssl req -x509 -new -nodes -key $CERTHOSTNAME.key -sha256 -days 365 -subj "/CN=$CERTHOSTNAME-CA" -out $CERTHOSTNAME-ca.crt
      
      - name: Generate CSR
        run: openssl req -new -key $CERTHOSTNAME.key -out $CERTHOSTNAME.csr -subj "/CN=$CERTHOSTNAME" -addext "subjectAltName=DNS:$CERTHOSTNAME,DNS:*.$CERTHOSTNAME"
      
      - name: Generate Expired Certificate
        # run: openssl x509 -req -in $CERTHOSTNAME.csr -CA $CERTHOSTNAME-ca.crt -CAkey $CERTHOSTNAME.key -CAcreateserial -out $CERTHOSTNAME-expired.crt -days -7 -sha256
        run: openssl ca -CA $CERTHOSTNAME-ca.crt -CAkey $CERTHOSTNAME.key -in $CERTHOSTNAME.csr -out $CERTHOSTNAME-expired.crt -startdate 202401010000Z -enddate 202404010000Z
      
      - name: Generate Valid Certificate
        run: openssl x509 -req -in $CERTHOSTNAME.csr -CA $CERTHOSTNAME-ca.crt -CAkey $CERTHOSTNAME.key -CAcreateserial -out $CERTHOSTNAME.crt -days 83 -sha256

      - name: Display Expiration Dates
        run: |
          echo "Expired Certificate Expiration Date:"
          openssl x509 -noout -enddate -in $CERTHOSTNAME-expired.crt
          openssl x509 -noout -enddate -in $CERTHOSTNAME-expired.crt >> $GITHUB_OUTPUT
          echo "Valid Certificate Expiration Date:"
          openssl x509 -noout -enddate -in $CERTHOSTNAME.crt
          openssl x509 -noout -enddate -in $CERTHOSTNAME.crt >> $GITHUB_OUTPUT
          
      # - name: Test
      #   run: bats -r .
